[package]
name = "proc_macro_days"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "*"
syn = { version = "*", features = ["extra-traits"] }
proc-macro2 = "*"
glob = "0.3.0"
regex = "1.7.0"
